site_name: Retrobatch JavaScript API

nav:
    - Introduction: index.md
    - Plug-In Basics: pluginanatomy.md
    - JS Expressions: jsexpressions.md
    - Asset API: assetapi.md
    - Image Accumulator API: accumulatorapi.md
    - Pixel Access: jstypedarrays.md
    - Document API: documentapi.md
    - Debugging: debugging.md
    - JavaScript Node: javascriptnode.md
    - Using Core Image: coreimage.md
    
theme:
    name: readthedocs
#    custom_dir: rbtheme/
